version: '3.8'

services:
  app:
    build:
      context: .  # Path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - postgres
    volumes:
      - .:/app  # If using TypeScript, you can use this to rebuild without rebuilding Docker
      - /app/node_modules
    command: ["npm", "start"]  # Optional: Ensure the correct start command

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
